package aard.launch;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

import aard.gui.GuiConsole;
import aard.telnet.Connector;

public class Start extends JFrame implements ActionListener {
    /** Generated by eclipse **/
    private static final long serialVersionUID = 1866978154005244719L;
    public static final Font FONT_CONSOLE = new Font("Courier New", Font.PLAIN, 16);
    
    private static Start INSTANCE;
    
    public GuiConsole console;
    public Connector connection;
    
    public Start(final String[] args) {
        // Currently no use for args
        this.setSize(640, 480);
        this.setTitle("Aardwolf");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        initComponents();
        
        //this.pack();
        this.setVisible(true);
        
        console.outAccess.print("Connecting...");
        this.connect();
    }
    
    private void initComponents() {
        this.add(this.console = new GuiConsole());
    }
    
    private void connect() {
        this.connection = new Connector(console);
        this.connection.connect();
    }
    
    public static Start getInstance() {
        return INSTANCE;
    }
    
    /** Start here! **/
    public static void main(final String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                INSTANCE = new Start(args);
            }
        });
    }
    
    @Override
    public void dispose() {
        super.dispose();
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
    }
}
